package com.google.android.gms.internal;

import com.google.android.gms.drive.metadata.MetadataField;
import com.google.android.gms.drive.metadata.internal.zzg;
import com.google.android.gms.drive.metadata.internal.zzm;
import com.google.android.gms.drive.metadata.internal.zzo;
import com.google.android.gms.drive.metadata.internal.zzp;
import com.google.android.gms.drive.metadata.internal.zzq;
import java.util.Collections;
import java.util.Set;

public class zznm
{
  public static final MetadataField zzasU;
  public static final MetadataField zzasV;
  public static final zznm.zza zzasW;
  public static final MetadataField zzasX;
  public static final MetadataField zzasY;
  public static final MetadataField zzasZ;
  public static final zznm.zzg zzatA;
  public static final zznm.zzh zzatB;
  public static final MetadataField zzatC;
  public static final MetadataField zzatD;
  public static final MetadataField zzatE;
  public static final com.google.android.gms.drive.metadata.internal.zzb zzatF;
  public static final MetadataField zzatG;
  public static final MetadataField zzatH;
  public static final zznm.zze zzatI;
  public static final MetadataField zzatJ;
  public static final MetadataField zzatK;
  public static final MetadataField zzata;
  public static final MetadataField zzatb;
  public static final MetadataField zzatc;
  public static final MetadataField zzatd;
  public static final MetadataField zzate;
  public static final MetadataField zzatf;
  public static final MetadataField zzatg;
  public static final MetadataField zzath;
  public static final MetadataField zzati;
  public static final zznm.zzb zzatj;
  public static final MetadataField zzatk;
  public static final MetadataField zzatl;
  public static final MetadataField zzatm;
  public static final MetadataField zzatn;
  public static final MetadataField zzato;
  public static final MetadataField zzatp;
  public static final MetadataField zzatq;
  public static final zznm.zzc zzatr;
  public static final MetadataField zzats;
  public static final com.google.android.gms.drive.metadata.zzb zzatt;
  public static final zzq zzatu;
  public static final zzq zzatv;
  public static final zzm zzatw;
  public static final zznm.zzd zzatx;
  public static final zznm.zzf zzaty;
  public static final MetadataField zzatz;
  
  static
  {
    int i = 4400000;
    int j = 6000000;
    int k = 7000000;
    int m = 4100000;
    int n = 4300000;
    zzasU = zznp.zzatS;
    Object localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("alternateLink", n);
    zzasV = (MetadataField)localObject;
    localObject = new com/google/android/gms/internal/zznm$zza;
    ((zznm.zza)localObject).<init>(5000000);
    zzasW = (zznm.zza)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("description", n);
    zzasX = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("embedLink", n);
    zzasY = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("fileExtension", n);
    zzasZ = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzg;
    ((zzg)localObject).<init>("fileSize", n);
    zzata = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("folderColorRgb", 7500000);
    zzatb = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("hasThumbnail", n);
    zzatc = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("indexableText", n);
    zzatd = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isAppData", n);
    zzate = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isCopyable", n);
    zzatf = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isEditable", m);
    zzatg = (MetadataField)localObject;
    localObject = new com/google/android/gms/internal/zznm$1;
    Set localSet1 = Collections.singleton("trashed");
    Set localSet2 = Collections.emptySet();
    ((zznm.1)localObject).<init>("isExplicitlyTrashed", localSet1, localSet2, k);
    zzath = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isLocalContentUpToDate", 7800000);
    zzati = (MetadataField)localObject;
    localObject = new com/google/android/gms/internal/zznm$zzb;
    ((zznm.zzb)localObject).<init>("isPinned", m);
    zzatj = (zznm.zzb)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isOpenable", 7200000);
    zzatk = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isRestricted", n);
    zzatl = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isShared", n);
    zzatm = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isGooglePhotosFolder", k);
    zzatn = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isGooglePhotosRootFolder", k);
    zzato = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isTrashable", i);
    zzatp = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("isViewed", n);
    zzatq = (MetadataField)localObject;
    localObject = new com/google/android/gms/internal/zznm$zzc;
    ((zznm.zzc)localObject).<init>(m);
    zzatr = (zznm.zzc)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("originalFilename", n);
    zzats = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzo;
    ((zzo)localObject).<init>("ownerNames", n);
    zzatt = (com.google.android.gms.drive.metadata.zzb)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzq;
    ((zzq)localObject).<init>("lastModifyingUser", j);
    zzatu = (zzq)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzq;
    ((zzq)localObject).<init>("sharingUser", j);
    zzatv = (zzq)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzm;
    ((zzm)localObject).<init>(m);
    zzatw = (zzm)localObject;
    localObject = new com/google/android/gms/internal/zznm$zzd;
    ((zznm.zzd)localObject).<init>("quotaBytesUsed", n);
    zzatx = (zznm.zzd)localObject;
    localObject = new com/google/android/gms/internal/zznm$zzf;
    ((zznm.zzf)localObject).<init>("starred", m);
    zzaty = (zznm.zzf)localObject;
    localObject = new com/google/android/gms/internal/zznm$2;
    localSet1 = Collections.emptySet();
    localSet2 = Collections.emptySet();
    ((zznm.2)localObject).<init>("thumbnail", localSet1, localSet2, i);
    zzatz = (MetadataField)localObject;
    localObject = new com/google/android/gms/internal/zznm$zzg;
    ((zznm.zzg)localObject).<init>("title", m);
    zzatA = (zznm.zzg)localObject;
    localObject = new com/google/android/gms/internal/zznm$zzh;
    ((zznm.zzh)localObject).<init>("trashed", m);
    zzatB = (zznm.zzh)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("webContentLink", n);
    zzatC = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("webViewLink", n);
    zzatD = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("uniqueIdentifier", 5000000);
    zzatE = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("writersCanShare", j);
    zzatF = (com.google.android.gms.drive.metadata.internal.zzb)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("role", j);
    zzatG = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("md5Checksum", k);
    zzatH = (MetadataField)localObject;
    localObject = new com/google/android/gms/internal/zznm$zze;
    ((zznm.zze)localObject).<init>(k);
    zzatI = (zznm.zze)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzp;
    ((zzp)localObject).<init>("recencyReason", 8000000);
    zzatJ = (MetadataField)localObject;
    localObject = new com/google/android/gms/drive/metadata/internal/zzb;
    ((com.google.android.gms.drive.metadata.internal.zzb)localObject).<init>("subscribed", 8000000);
    zzatK = (MetadataField)localObject;
  }
}


/* Location:              C:\Users\haryo\Desktop\enjarify-master\presensi-enjarify.jar!\com\google\android\gms\internal\zznm.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */