package com.google.android.gms.internal;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class zznu
{
  public static final Set AGGREGATE_INPUT_TYPES;
  private static final Map zzawC;
  public static final zzsy.zza zzayA;
  public static final zzsy.zza zzayB;
  public static final zzsy.zza zzayC;
  public static final zzsy.zza zzayD;
  public static final zzsy.zza zzayE;
  public static final zzsy.zza zzayF;
  public static final zzsy.zza zzayG;
  public static final zzsy.zza zzayH;
  public static final zzsy.zza zzayI;
  public static final zzsy.zza zzayJ;
  public static final zzsy.zza zzayK;
  public static final zzsy.zza zzayL;
  public static final zzsy.zza zzayM;
  public static final zzsy.zza zzayN;
  public static final zzsy.zza zzayO;
  public static final zzsy.zza zzayP;
  public static final zzsy.zza zzayQ;
  public static final zzsy.zza zzayR;
  public static final zzsy.zza zzayS;
  public static final zzsy.zza zzayT;
  public static final zzsy.zza zzayU;
  public static final zzsy.zza zzayV;
  public static final zzsy.zza zzayW;
  public static final zzsy.zza zzayX;
  public static final zzsy.zza zzayY;
  public static final zzsy.zza zzayZ;
  public static final zzsy.zza zzaza;
  public static final zzsy.zza zzazb;
  public static final zzsy.zza zzazc;
  public static final zzsy.zza zzazd;
  public static final zzsy.zza zzaze;
  public static final zzsy.zza zzazf;
  public static final zzsy.zza zzazg;
  public static final zzsy.zza zzazh;
  public static final zzsy.zza zzazi;
  public static final zzsy.zza zzazj;
  public static final zzsy.zza zzazk;
  public static final zzsy.zza zzazl;
  public static final zzsy.zza zzazm;
  public static final zzsy.zza zzazn;
  public static final zzsy.zza zzazo;
  public static final zzsy.zza zzazp;
  public static final zzsy.zza zzazq;
  public static final zzsy.zza zzazr;
  public static final zzsy.zza zzazs;
  public static final zzsy.zza zzazt;
  public static final zzsy.zza zzazu;
  public static final String[] zzazv;
  private static final Map zzazw;
  
  static
  {
    int i = 4;
    int j = 3;
    int k = 2;
    int m = 1;
    Object localObject1 = new zzsy.zzb[m];
    Object localObject2 = zznt.zzaxz;
    localObject1[0] = localObject2;
    zzayA = zza("com.google.step_count.delta", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxz;
    localObject1[0] = localObject2;
    zzayB = zza("com.google.step_count.cumulative", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxR;
    localObject1[0] = localObject2;
    zzayC = zza("com.google.step_count.cadence", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxw;
    localObject1[0] = localObject2;
    zzayD = zza("com.google.activity.segment", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[i];
    localObject2 = zznt.zzaxw;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzaxx;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzaxY;
    localObject1[k] = localObject2;
    localObject2 = zznt.zzayb;
    localObject1[j] = localObject2;
    zzayE = zza("com.google.floor_change", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxT;
    localObject1[0] = localObject2;
    zzayF = zza("com.google.calories.consumed", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxT;
    localObject1[0] = localObject2;
    zzayG = zza("com.google.calories.expended", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxT;
    localObject1[0] = localObject2;
    zzayH = zza("com.google.calories.bmr", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxU;
    localObject1[0] = localObject2;
    zzayI = zza("com.google.power.sample", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[k];
    localObject2 = zznt.zzaxw;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzaxx;
    localObject1[m] = localObject2;
    zzayJ = zza("com.google.activity.sample", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayq;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayr;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzays;
    localObject1[k] = localObject2;
    zzayK = zza("com.google.accelerometer", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayv;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayt;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayu;
    localObject1[k] = localObject2;
    zzayL = zza("com.google.sensor.events", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxK;
    localObject1[0] = localObject2;
    zzayM = zza("com.google.internal.goal", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxE;
    localObject1[0] = localObject2;
    zzayN = zza("com.google.heart_rate.bpm", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[i];
    localObject2 = zznt.zzaxF;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzaxG;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzaxH;
    localObject1[k] = localObject2;
    localObject2 = zznt.zzaxI;
    localObject1[j] = localObject2;
    zzayO = zza("com.google.location.sample", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[i];
    localObject2 = zznt.zzaxF;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzaxG;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzaxH;
    localObject1[k] = localObject2;
    localObject2 = zznt.zzaxI;
    localObject1[j] = localObject2;
    zzayP = zza("com.google.location.track", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxJ;
    localObject1[0] = localObject2;
    zzayQ = zza("com.google.distance.delta", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxJ;
    localObject1[0] = localObject2;
    zzayR = zza("com.google.distance.cumulative", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxQ;
    localObject1[0] = localObject2;
    zzayS = zza("com.google.speed", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxS;
    localObject1[0] = localObject2;
    zzayT = zza("com.google.cycling.wheel_revolution.cumulative", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxR;
    localObject1[0] = localObject2;
    zzayU = zza("com.google.cycling.wheel_revolution.rpm", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxS;
    localObject1[0] = localObject2;
    zzayV = zza("com.google.cycling.pedaling.cumulative", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxR;
    localObject1[0] = localObject2;
    zzayW = zza("com.google.cycling.pedaling.cadence", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxM;
    localObject1[0] = localObject2;
    zzayX = zza("com.google.height", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxN;
    localObject1[0] = localObject2;
    zzayY = zza("com.google.weight", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxP;
    localObject1[0] = localObject2;
    zzayZ = zza("com.google.body.fat.percentage", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxO;
    localObject1[0] = localObject2;
    zzaza = zza("com.google.body.waist.circumference", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[m];
    localObject2 = zznt.zzaxO;
    localObject1[0] = localObject2;
    zzazb = zza("com.google.body.hip.circumference", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzaxX;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzaxV;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzaxW;
    localObject1[k] = localObject2;
    zzazc = zza("com.google.nutrition", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[5];
    localObject2 = zznt.zzaye;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayf;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzaxA;
    localObject1[k] = localObject2;
    localObject2 = zznt.zzayh;
    localObject1[j] = localObject2;
    localObject2 = zznt.zzayg;
    localObject1[i] = localObject2;
    zzazd = zza("com.google.activity.exercise", (zzsy.zzb[])localObject1);
    Object localObject3 = new java/util/HashSet;
    localObject1 = new String[11];
    localObject2 = zzayD.name;
    localObject1[0] = localObject2;
    localObject2 = zzayF.name;
    localObject1[m] = localObject2;
    localObject2 = zzayG.name;
    localObject1[k] = localObject2;
    localObject2 = zzayQ.name;
    localObject1[j] = localObject2;
    localObject2 = zzayE.name;
    localObject1[i] = localObject2;
    Object localObject4 = zzayN.name;
    localObject1[5] = localObject4;
    localObject4 = zzayO.name;
    localObject1[6] = localObject4;
    localObject4 = zzazc.name;
    localObject1[7] = localObject4;
    localObject4 = zzayS.name;
    localObject1[8] = localObject4;
    localObject4 = zzayA.name;
    localObject1[9] = localObject4;
    localObject4 = zzayY.name;
    localObject1[10] = localObject4;
    localObject1 = Arrays.asList((Object[])localObject1);
    ((HashSet)localObject3).<init>((Collection)localObject1);
    AGGREGATE_INPUT_TYPES = Collections.unmodifiableSet((Set)localObject3);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzaxw;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzaxA;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayi;
    localObject1[k] = localObject2;
    zzaze = zza("com.google.activity.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[6];
    localObject2 = zznt.zzaxC;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzaxD;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzaxZ;
    localObject1[k] = localObject2;
    localObject2 = zznt.zzaya;
    localObject1[j] = localObject2;
    localObject2 = zznt.zzayc;
    localObject1[i] = localObject2;
    localObject4 = zznt.zzayd;
    localObject1[5] = localObject4;
    zzazf = zza("com.google.floor_change.summary", (zzsy.zzb[])localObject1);
    zzazg = zzayA;
    zzazh = zzayQ;
    zzazi = zzayF;
    zzazj = zzayG;
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayj;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayk;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayl;
    localObject1[k] = localObject2;
    zzazk = zza("com.google.heart_rate.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[i];
    localObject2 = zznt.zzaym;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayn;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayo;
    localObject1[k] = localObject2;
    localObject2 = zznt.zzayp;
    localObject1[j] = localObject2;
    zzazl = zza("com.google.location.bounding_box", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayj;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayk;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayl;
    localObject1[k] = localObject2;
    zzazm = zza("com.google.power.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayj;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayk;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayl;
    localObject1[k] = localObject2;
    zzazn = zza("com.google.speed.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayj;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayk;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayl;
    localObject1[k] = localObject2;
    zzazo = zza("com.google.weight.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayj;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayk;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayl;
    localObject1[k] = localObject2;
    zzazp = zza("com.google.calories.bmr.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayj;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayk;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayl;
    localObject1[k] = localObject2;
    zzazq = zza("com.google.body.fat.percentage.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayj;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayk;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayl;
    localObject1[k] = localObject2;
    zzazr = zza("com.google.body.hip.circumference.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[j];
    localObject2 = zznt.zzayj;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzayk;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayl;
    localObject1[k] = localObject2;
    zzazs = zza("com.google.body.waist.circumference.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[k];
    localObject2 = zznt.zzaxX;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzaxV;
    localObject1[m] = localObject2;
    zzazt = zza("com.google.nutrition.summary", (zzsy.zzb[])localObject1);
    localObject1 = new zzsy.zzb[5];
    localObject2 = zznt.zzayw;
    localObject1[0] = localObject2;
    localObject2 = zznt.zzaxw;
    localObject1[m] = localObject2;
    localObject2 = zznt.zzayx;
    localObject1[k] = localObject2;
    localObject2 = zznt.zzayy;
    localObject1[j] = localObject2;
    localObject2 = zznt.zzayz;
    localObject1[i] = localObject2;
    zzazu = zza("com.google.internal.session", (zzsy.zzb[])localObject1);
    zzawC = zzuF();
    localObject3 = new String[43];
    localObject3[0] = "com.google.accelerometer";
    localObject3[m] = "com.google.activity.exercise";
    localObject3[k] = "com.google.activity.sample";
    localObject3[j] = "com.google.activity.segment";
    localObject3[i] = "com.google.activity.summary";
    localObject3[5] = "com.google.body.fat.percentage";
    localObject3[6] = "com.google.body.fat.percentage.summary";
    localObject3[7] = "com.google.body.hip.circumference";
    localObject3[8] = "com.google.body.hip.circumference.summary";
    localObject3[9] = "com.google.body.waist.circumference";
    localObject3[10] = "com.google.body.waist.circumference.summary";
    localObject3[11] = "com.google.calories.bmr";
    localObject3[12] = "com.google.calories.bmr.summary";
    localObject3[13] = "com.google.calories.consumed";
    localObject3[14] = "com.google.calories.expended";
    localObject3[15] = "com.google.cycling.pedaling.cadence";
    localObject3[16] = "com.google.cycling.pedaling.cumulative";
    localObject3[17] = "com.google.cycling.wheel_revolution.cumulative";
    localObject3[18] = "com.google.cycling.wheel_revolution.rpm";
    localObject3[19] = "com.google.distance.cumulative";
    localObject3[20] = "com.google.distance.delta";
    localObject3[21] = "com.google.floor_change";
    localObject3[22] = "com.google.floor_change.summary";
    localObject3[23] = "com.google.heart_rate.bpm";
    localObject3[24] = "com.google.heart_rate.summary";
    localObject3[25] = "com.google.height";
    localObject3[26] = "com.google.internal.goal";
    localObject3[27] = "com.google.internal.session";
    localObject3[28] = "com.google.location.bounding_box";
    localObject3[29] = "com.google.location.sample";
    localObject3[30] = "com.google.location.track";
    localObject3[31] = "com.google.nutrition";
    localObject3[32] = "com.google.nutrition.summary";
    localObject3[33] = "com.google.power.sample";
    localObject3[34] = "com.google.power.summary";
    localObject3[35] = "com.google.sensor.events";
    localObject3[36] = "com.google.speed";
    localObject3[37] = "com.google.speed.summary";
    localObject3[38] = "com.google.step_count.cadence";
    localObject3[39] = "com.google.step_count.cumulative";
    localObject3[40] = "com.google.step_count.delta";
    localObject3[41] = "com.google.weight";
    localObject3[42] = "com.google.weight.summary";
    zzazv = (String[])localObject3;
    localObject3 = new java/util/HashSet;
    ((HashSet)localObject3).<init>();
    localObject1 = zzayB;
    ((Set)localObject3).add(localObject1);
    localObject1 = zzayR;
    ((Set)localObject3).add(localObject1);
    localObject1 = zzayV;
    ((Set)localObject3).add(localObject1);
    localObject1 = new java/util/HashSet;
    ((HashSet)localObject1).<init>();
    localObject2 = zzayQ;
    ((Set)localObject1).add(localObject2);
    localObject2 = zzayA;
    ((Set)localObject1).add(localObject2);
    localObject2 = zzayG;
    ((Set)localObject1).add(localObject2);
    localObject2 = zzayF;
    ((Set)localObject1).add(localObject2);
    localObject2 = zzayE;
    ((Set)localObject1).add(localObject2);
    localObject2 = new java/util/HashSet;
    ((HashSet)localObject2).<init>();
    localObject4 = zzayZ;
    ((Set)localObject2).add(localObject4);
    localObject4 = zzazb;
    ((Set)localObject2).add(localObject4);
    localObject4 = zzaza;
    ((Set)localObject2).add(localObject4);
    localObject4 = zzazc;
    ((Set)localObject2).add(localObject4);
    localObject4 = zzayX;
    ((Set)localObject2).add(localObject4);
    localObject4 = zzayY;
    ((Set)localObject2).add(localObject4);
    localObject4 = zzayN;
    ((Set)localObject2).add(localObject4);
    localObject4 = new java/util/HashMap;
    ((HashMap)localObject4).<init>();
    zznu.zza localzza = zznu.zza.zzazx;
    zza((Map)localObject4, (Collection)localObject3, localzza);
    localObject3 = zznu.zza.zzazy;
    zza((Map)localObject4, (Collection)localObject1, (zznu.zza)localObject3);
    localObject3 = zznu.zza.zzazz;
    zza((Map)localObject4, (Collection)localObject2, (zznu.zza)localObject3);
    zzazw = Collections.unmodifiableMap((Map)localObject4);
  }
  
  public static zzsy.zza zza(String paramString, zzsy.zzb... paramVarArgs)
  {
    zzsy.zza localzza = new com/google/android/gms/internal/zzsy$zza;
    localzza.<init>();
    localzza.name = paramString;
    localzza.zzbuE = paramVarArgs;
    return localzza;
  }
  
  private static void zza(Map paramMap, Collection paramCollection, zznu.zza paramzza)
  {
    Iterator localIterator = paramCollection.iterator();
    for (;;)
    {
      boolean bool = localIterator.hasNext();
      if (!bool) {
        break;
      }
      zzsy.zza localzza = (zzsy.zza)localIterator.next();
      paramMap.put(localzza, paramzza);
    }
  }
  
  public static boolean zzdD(String paramString)
  {
    String[] arrayOfString = zzazv;
    int i = Arrays.binarySearch(arrayOfString, paramString);
    if (i >= 0) {
      i = 1;
    }
    for (;;)
    {
      return i;
      int j = 0;
      arrayOfString = null;
    }
  }
  
  private static Map zzuF()
  {
    HashMap localHashMap = new java/util/HashMap;
    localHashMap.<init>();
    String str = zzayD.name;
    List localList = Collections.singletonList(zzaze);
    localHashMap.put(str, localList);
    str = zzayF.name;
    localList = Collections.singletonList(zzazi);
    localHashMap.put(str, localList);
    str = zzayG.name;
    localList = Collections.singletonList(zzazj);
    localHashMap.put(str, localList);
    str = zzayQ.name;
    localList = Collections.singletonList(zzazh);
    localHashMap.put(str, localList);
    str = zzayE.name;
    localList = Collections.singletonList(zzazf);
    localHashMap.put(str, localList);
    str = zzayO.name;
    localList = Collections.singletonList(zzazl);
    localHashMap.put(str, localList);
    str = zzayI.name;
    localList = Collections.singletonList(zzazm);
    localHashMap.put(str, localList);
    str = zzayN.name;
    localList = Collections.singletonList(zzazk);
    localHashMap.put(str, localList);
    str = zzayS.name;
    localList = Collections.singletonList(zzazn);
    localHashMap.put(str, localList);
    str = zzayA.name;
    localList = Collections.singletonList(zzazg);
    localHashMap.put(str, localList);
    str = zzayY.name;
    localList = Collections.singletonList(zzazo);
    localHashMap.put(str, localList);
    return localHashMap;
  }
}


/* Location:              C:\Users\haryo\Desktop\enjarify-master\presensi-enjarify.jar!\com\google\android\gms\internal\zznu.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */