package org.apache.http.impl.auth;

class NTLMEngineImpl$MD4
{
  protected int A = 1732584193;
  protected int B = -271733879;
  protected int C = -1732584194;
  protected int D = 271733878;
  protected long count = 0L;
  protected byte[] dataBuffer;
  
  NTLMEngineImpl$MD4()
  {
    byte[] arrayOfByte = new byte[64];
    this.dataBuffer = arrayOfByte;
  }
  
  byte[] getOutput()
  {
    int i = 8;
    long l1 = this.count;
    long l2 = 63;
    l1 &= l2;
    int j = (int)l1;
    int k = 56;
    if (j < k) {}
    byte[] arrayOfByte1;
    for (j = 56 - j;; j = 120 - j)
    {
      arrayOfByte1 = new byte[j + 8];
      arrayOfByte1[0] = Byte.MIN_VALUE;
      k = 0;
      while (k < i)
      {
        int m = j + k;
        long l3 = this.count;
        long l4 = 8;
        l3 *= l4;
        int n = k * 8;
        l3 >>>= n;
        n = (byte)(int)l3;
        arrayOfByte1[m] = n;
        k += 1;
      }
    }
    update(arrayOfByte1);
    byte[] arrayOfByte2 = new byte[16];
    k = this.A;
    NTLMEngineImpl.writeULong(arrayOfByte2, k, 0);
    k = this.B;
    NTLMEngineImpl.writeULong(arrayOfByte2, k, 4);
    k = this.C;
    NTLMEngineImpl.writeULong(arrayOfByte2, k, i);
    k = this.D;
    NTLMEngineImpl.writeULong(arrayOfByte2, k, 12);
    return arrayOfByte2;
  }
  
  protected void processBuffer()
  {
    int i = 16;
    int[] arrayOfInt = new int[i];
    int j = 0;
    while (j < i)
    {
      byte[] arrayOfByte1 = this.dataBuffer;
      k = j * 4;
      m = arrayOfByte1[k] & 0xFF;
      byte[] arrayOfByte2 = this.dataBuffer;
      n = j * 4 + 1;
      k = (arrayOfByte2[n] & 0xFF) << 8;
      m += k;
      arrayOfByte2 = this.dataBuffer;
      n = j * 4 + 2;
      k = (arrayOfByte2[n] & 0xFF) << 16;
      m += k;
      arrayOfByte2 = this.dataBuffer;
      n = j * 4 + 3;
      k = (arrayOfByte2[n] & 0xFF) << 24;
      m += k;
      arrayOfInt[j] = m;
      j += 1;
    }
    j = this.A;
    int m = this.B;
    int k = this.C;
    int n = this.D;
    round1(arrayOfInt);
    round2(arrayOfInt);
    round3(arrayOfInt);
    int i1 = this.A;
    j += i1;
    this.A = j;
    j = this.B + m;
    this.B = j;
    j = this.C + k;
    this.C = j;
    j = this.D + n;
    this.D = j;
  }
  
  protected void round1(int[] paramArrayOfInt)
  {
    int i = 19;
    int j = 11;
    int k = 7;
    int m = 3;
    int n = this.A;
    int i1 = this.B;
    int i2 = this.C;
    int i3 = this.D;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[0];
    n = NTLMEngineImpl.rotintlft(n + i1, m);
    this.A = n;
    n = this.D;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[1];
    n = NTLMEngineImpl.rotintlft(n + i1, k);
    this.D = n;
    n = this.C;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[2];
    n = NTLMEngineImpl.rotintlft(n + i1, j);
    this.C = n;
    n = this.B;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[m];
    n = NTLMEngineImpl.rotintlft(n + i1, i);
    this.B = n;
    n = this.A;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[4];
    n = NTLMEngineImpl.rotintlft(n + i1, m);
    this.A = n;
    n = this.D;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[5];
    n = NTLMEngineImpl.rotintlft(n + i1, k);
    this.D = n;
    n = this.C;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[6];
    n = NTLMEngineImpl.rotintlft(n + i1, j);
    this.C = n;
    n = this.B;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[k];
    n = NTLMEngineImpl.rotintlft(n + i1, i);
    this.B = n;
    n = this.A;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[8];
    n = NTLMEngineImpl.rotintlft(n + i1, m);
    this.A = n;
    n = this.D;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[9];
    n = NTLMEngineImpl.rotintlft(n + i1, k);
    this.D = n;
    n = this.C;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[10];
    n = NTLMEngineImpl.rotintlft(n + i1, j);
    this.C = n;
    n = this.B;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[j];
    n = NTLMEngineImpl.rotintlft(n + i1, i);
    this.B = n;
    n = this.A;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[12];
    n = NTLMEngineImpl.rotintlft(n + i1, m);
    this.A = n;
    n = this.D;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[13];
    n = NTLMEngineImpl.rotintlft(n + i1, k);
    this.D = n;
    n = this.C;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[14];
    n = NTLMEngineImpl.rotintlft(n + i1, j);
    this.C = n;
    n = this.B;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i1 = NTLMEngineImpl.F(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[15];
    n = NTLMEngineImpl.rotintlft(n + i1, i);
    this.B = n;
  }
  
  protected void round2(int[] paramArrayOfInt)
  {
    int i = 13;
    int j = 9;
    int k = 5;
    int m = 3;
    int n = 1518500249;
    int i1 = this.A;
    int i2 = this.B;
    int i3 = this.C;
    int i4 = this.D;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[0];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, m);
    this.A = i1;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i4 = this.C;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[4];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, k);
    this.D = i1;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i4 = this.B;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[8];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, j);
    this.C = i1;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i4 = this.A;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[12];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, i);
    this.B = i1;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i4 = this.D;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[1];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, m);
    this.A = i1;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i4 = this.C;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[k];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, k);
    this.D = i1;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i4 = this.B;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[j];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, j);
    this.C = i1;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i4 = this.A;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[i];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, i);
    this.B = i1;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i4 = this.D;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[2];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, m);
    this.A = i1;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i4 = this.C;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[6];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, k);
    this.D = i1;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i4 = this.B;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[10];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, j);
    this.C = i1;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i4 = this.A;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[14];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, i);
    this.B = i1;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i4 = this.D;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[m];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, m);
    this.A = i1;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i4 = this.C;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[7];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, k);
    this.D = i1;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i4 = this.B;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[11];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, j);
    this.C = i1;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i4 = this.A;
    i2 = NTLMEngineImpl.G(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[15];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, i);
    this.B = i1;
  }
  
  protected void round3(int[] paramArrayOfInt)
  {
    int i = 15;
    int j = 11;
    int k = 9;
    int m = 3;
    int n = 1859775393;
    int i1 = this.A;
    int i2 = this.B;
    int i3 = this.C;
    int i4 = this.D;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[0];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, m);
    this.A = i1;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i4 = this.C;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[8];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, k);
    this.D = i1;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i4 = this.B;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[4];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, j);
    this.C = i1;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i4 = this.A;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[12];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, i);
    this.B = i1;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i4 = this.D;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[2];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, m);
    this.A = i1;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i4 = this.C;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[10];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, k);
    this.D = i1;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i4 = this.B;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[6];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, j);
    this.C = i1;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i4 = this.A;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[14];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, i);
    this.B = i1;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i4 = this.D;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[1];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, m);
    this.A = i1;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i4 = this.C;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[k];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, k);
    this.D = i1;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i4 = this.B;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[5];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, j);
    this.C = i1;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i4 = this.A;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[13];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, i);
    this.B = i1;
    i1 = this.A;
    i2 = this.B;
    i3 = this.C;
    i4 = this.D;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[m];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, m);
    this.A = i1;
    i1 = this.D;
    i2 = this.A;
    i3 = this.B;
    i4 = this.C;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[j];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, k);
    this.D = i1;
    i1 = this.C;
    i2 = this.D;
    i3 = this.A;
    i4 = this.B;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[7];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, j);
    this.C = i1;
    i1 = this.B;
    i2 = this.C;
    i3 = this.D;
    i4 = this.A;
    i2 = NTLMEngineImpl.H(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[i];
    i1 = NTLMEngineImpl.rotintlft(i1 + i2 + n, i);
    this.B = i1;
  }
  
  void update(byte[] paramArrayOfByte)
  {
    int i = 0;
    long l1 = this.count;
    long l2 = 63;
    l1 &= l2;
    int j = (int)l1;
    int k = 0;
    byte[] arrayOfByte2;
    long l3;
    for (;;)
    {
      int m = paramArrayOfByte.length - k + j;
      byte[] arrayOfByte1 = this.dataBuffer;
      int n = arrayOfByte1.length;
      if (m < n) {
        break;
      }
      arrayOfByte2 = this.dataBuffer;
      m = arrayOfByte2.length - j;
      arrayOfByte1 = this.dataBuffer;
      System.arraycopy(paramArrayOfByte, k, arrayOfByte1, j, m);
      l2 = this.count;
      l3 = m;
      l2 += l3;
      this.count = l2;
      k += m;
      processBuffer();
      j = 0;
    }
    i = paramArrayOfByte.length;
    if (k < i)
    {
      i = paramArrayOfByte.length - k;
      arrayOfByte2 = this.dataBuffer;
      System.arraycopy(paramArrayOfByte, k, arrayOfByte2, j, i);
      l2 = this.count;
      l3 = i;
      l2 += l3;
      this.count = l2;
      k = j + i;
    }
  }
}


/* Location:              C:\Users\haryo\Desktop\enjarify-master\presensi-enjarify.jar!\org\apache\http\impl\auth\NTLMEngineImpl$MD4.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */