package b.a.a.a.i.a;

class j$c
{
  protected int a = 1732584193;
  protected int b = -271733879;
  protected int c = -1732584194;
  protected int d = 271733878;
  protected long e = 0L;
  protected byte[] f;
  
  j$c()
  {
    byte[] arrayOfByte = new byte[64];
    this.f = arrayOfByte;
  }
  
  void a(byte[] paramArrayOfByte)
  {
    int i = 0;
    long l1 = this.e;
    long l2 = 63;
    l1 &= l2;
    int j = (int)l1;
    int k = 0;
    byte[] arrayOfByte2;
    long l3;
    for (;;)
    {
      int m = paramArrayOfByte.length - k + j;
      byte[] arrayOfByte1 = this.f;
      int n = arrayOfByte1.length;
      if (m < n) {
        break;
      }
      arrayOfByte2 = this.f;
      m = arrayOfByte2.length - j;
      arrayOfByte1 = this.f;
      System.arraycopy(paramArrayOfByte, k, arrayOfByte1, j, m);
      l2 = this.e;
      l3 = m;
      l2 += l3;
      this.e = l2;
      k += m;
      b();
      j = 0;
    }
    i = paramArrayOfByte.length;
    if (k < i)
    {
      i = paramArrayOfByte.length - k;
      arrayOfByte2 = this.f;
      System.arraycopy(paramArrayOfByte, k, arrayOfByte2, j, i);
      l2 = this.e;
      l3 = i;
      l2 += l3;
      this.e = l2;
      k = j + i;
    }
  }
  
  protected void a(int[] paramArrayOfInt)
  {
    int i = 19;
    int j = 11;
    int k = 7;
    int m = 3;
    int n = this.a;
    int i1 = this.b;
    int i2 = this.c;
    int i3 = this.d;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[0];
    n = j.a(n + i1, m);
    this.a = n;
    n = this.d;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[1];
    n = j.a(n + i1, k);
    this.d = n;
    n = this.c;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[2];
    n = j.a(n + i1, j);
    this.c = n;
    n = this.b;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[m];
    n = j.a(n + i1, i);
    this.b = n;
    n = this.a;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[4];
    n = j.a(n + i1, m);
    this.a = n;
    n = this.d;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[5];
    n = j.a(n + i1, k);
    this.d = n;
    n = this.c;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[6];
    n = j.a(n + i1, j);
    this.c = n;
    n = this.b;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[k];
    n = j.a(n + i1, i);
    this.b = n;
    n = this.a;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[8];
    n = j.a(n + i1, m);
    this.a = n;
    n = this.d;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[9];
    n = j.a(n + i1, k);
    this.d = n;
    n = this.c;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[10];
    n = j.a(n + i1, j);
    this.c = n;
    n = this.b;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[j];
    n = j.a(n + i1, i);
    this.b = n;
    n = this.a;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[12];
    n = j.a(n + i1, m);
    this.a = n;
    n = this.d;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[13];
    n = j.a(n + i1, k);
    this.d = n;
    n = this.c;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[14];
    n = j.a(n + i1, j);
    this.c = n;
    n = this.b;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i1 = j.a(i1, i2, i3);
    n += i1;
    i1 = paramArrayOfInt[15];
    n = j.a(n + i1, i);
    this.b = n;
  }
  
  byte[] a()
  {
    int i = 8;
    long l1 = this.e;
    long l2 = 63;
    l1 &= l2;
    int j = (int)l1;
    int k = 56;
    if (j < k) {}
    byte[] arrayOfByte1;
    for (j = 56 - j;; j = 120 - j)
    {
      arrayOfByte1 = new byte[j + 8];
      arrayOfByte1[0] = Byte.MIN_VALUE;
      k = 0;
      while (k < i)
      {
        int m = j + k;
        long l3 = this.e;
        long l4 = 8;
        l3 *= l4;
        int n = k * 8;
        l3 >>>= n;
        n = (byte)(int)l3;
        arrayOfByte1[m] = n;
        k += 1;
      }
    }
    a(arrayOfByte1);
    byte[] arrayOfByte2 = new byte[16];
    k = this.a;
    j.a(arrayOfByte2, k, 0);
    k = this.b;
    j.a(arrayOfByte2, k, 4);
    k = this.c;
    j.a(arrayOfByte2, k, i);
    k = this.d;
    j.a(arrayOfByte2, k, 12);
    return arrayOfByte2;
  }
  
  protected void b()
  {
    int i = 16;
    int[] arrayOfInt = new int[i];
    int j = 0;
    while (j < i)
    {
      byte[] arrayOfByte1 = this.f;
      k = j * 4;
      m = arrayOfByte1[k] & 0xFF;
      byte[] arrayOfByte2 = this.f;
      n = j * 4 + 1;
      k = (arrayOfByte2[n] & 0xFF) << 8;
      m += k;
      arrayOfByte2 = this.f;
      n = j * 4 + 2;
      k = (arrayOfByte2[n] & 0xFF) << 16;
      m += k;
      arrayOfByte2 = this.f;
      n = j * 4 + 3;
      k = (arrayOfByte2[n] & 0xFF) << 24;
      m += k;
      arrayOfInt[j] = m;
      j += 1;
    }
    j = this.a;
    int m = this.b;
    int k = this.c;
    int n = this.d;
    a(arrayOfInt);
    b(arrayOfInt);
    c(arrayOfInt);
    int i1 = this.a;
    j += i1;
    this.a = j;
    j = this.b + m;
    this.b = j;
    j = this.c + k;
    this.c = j;
    j = this.d + n;
    this.d = j;
  }
  
  protected void b(int[] paramArrayOfInt)
  {
    int i = 13;
    int j = 9;
    int k = 5;
    int m = 3;
    int n = 1518500249;
    int i1 = this.a;
    int i2 = this.b;
    int i3 = this.c;
    int i4 = this.d;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[0];
    i1 = j.a(i1 + i2 + n, m);
    this.a = i1;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i4 = this.c;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[4];
    i1 = j.a(i1 + i2 + n, k);
    this.d = i1;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i4 = this.b;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[8];
    i1 = j.a(i1 + i2 + n, j);
    this.c = i1;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i4 = this.a;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[12];
    i1 = j.a(i1 + i2 + n, i);
    this.b = i1;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i4 = this.d;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[1];
    i1 = j.a(i1 + i2 + n, m);
    this.a = i1;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i4 = this.c;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[k];
    i1 = j.a(i1 + i2 + n, k);
    this.d = i1;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i4 = this.b;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[j];
    i1 = j.a(i1 + i2 + n, j);
    this.c = i1;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i4 = this.a;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[i];
    i1 = j.a(i1 + i2 + n, i);
    this.b = i1;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i4 = this.d;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[2];
    i1 = j.a(i1 + i2 + n, m);
    this.a = i1;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i4 = this.c;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[6];
    i1 = j.a(i1 + i2 + n, k);
    this.d = i1;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i4 = this.b;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[10];
    i1 = j.a(i1 + i2 + n, j);
    this.c = i1;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i4 = this.a;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[14];
    i1 = j.a(i1 + i2 + n, i);
    this.b = i1;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i4 = this.d;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[m];
    i1 = j.a(i1 + i2 + n, m);
    this.a = i1;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i4 = this.c;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[7];
    i1 = j.a(i1 + i2 + n, k);
    this.d = i1;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i4 = this.b;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[11];
    i1 = j.a(i1 + i2 + n, j);
    this.c = i1;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i4 = this.a;
    i2 = j.b(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[15];
    i1 = j.a(i1 + i2 + n, i);
    this.b = i1;
  }
  
  protected void c(int[] paramArrayOfInt)
  {
    int i = 15;
    int j = 11;
    int k = 9;
    int m = 3;
    int n = 1859775393;
    int i1 = this.a;
    int i2 = this.b;
    int i3 = this.c;
    int i4 = this.d;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[0];
    i1 = j.a(i1 + i2 + n, m);
    this.a = i1;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i4 = this.c;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[8];
    i1 = j.a(i1 + i2 + n, k);
    this.d = i1;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i4 = this.b;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[4];
    i1 = j.a(i1 + i2 + n, j);
    this.c = i1;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i4 = this.a;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[12];
    i1 = j.a(i1 + i2 + n, i);
    this.b = i1;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i4 = this.d;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[2];
    i1 = j.a(i1 + i2 + n, m);
    this.a = i1;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i4 = this.c;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[10];
    i1 = j.a(i1 + i2 + n, k);
    this.d = i1;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i4 = this.b;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[6];
    i1 = j.a(i1 + i2 + n, j);
    this.c = i1;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i4 = this.a;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[14];
    i1 = j.a(i1 + i2 + n, i);
    this.b = i1;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i4 = this.d;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[1];
    i1 = j.a(i1 + i2 + n, m);
    this.a = i1;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i4 = this.c;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[k];
    i1 = j.a(i1 + i2 + n, k);
    this.d = i1;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i4 = this.b;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[5];
    i1 = j.a(i1 + i2 + n, j);
    this.c = i1;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i4 = this.a;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[13];
    i1 = j.a(i1 + i2 + n, i);
    this.b = i1;
    i1 = this.a;
    i2 = this.b;
    i3 = this.c;
    i4 = this.d;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[m];
    i1 = j.a(i1 + i2 + n, m);
    this.a = i1;
    i1 = this.d;
    i2 = this.a;
    i3 = this.b;
    i4 = this.c;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[j];
    i1 = j.a(i1 + i2 + n, k);
    this.d = i1;
    i1 = this.c;
    i2 = this.d;
    i3 = this.a;
    i4 = this.b;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[7];
    i1 = j.a(i1 + i2 + n, j);
    this.c = i1;
    i1 = this.b;
    i2 = this.c;
    i3 = this.d;
    i4 = this.a;
    i2 = j.c(i2, i3, i4);
    i1 += i2;
    i2 = paramArrayOfInt[i];
    i1 = j.a(i1 + i2 + n, i);
    this.b = i1;
  }
}


/* Location:              C:\Users\haryo\Desktop\enjarify-master\presensi-enjarify.jar!\b\a\a\a\i\a\j$c.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */