package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzr
  extends OptionalPendingResult
{
  private final zzb zzaiy;
  
  public zzr(PendingResult paramPendingResult)
  {
    boolean bool = paramPendingResult instanceof zzb;
    if (!bool)
    {
      IllegalArgumentException localIllegalArgumentException = new java/lang/IllegalArgumentException;
      localIllegalArgumentException.<init>("OptionalPendingResult can only wrap PendingResults generated by an API call.");
      throw localIllegalArgumentException;
    }
    paramPendingResult = (zzb)paramPendingResult;
    this.zzaiy = paramPendingResult;
  }
  
  public Result await()
  {
    return this.zzaiy.await();
  }
  
  public Result await(long paramLong, TimeUnit paramTimeUnit)
  {
    return this.zzaiy.await(paramLong, paramTimeUnit);
  }
  
  public void cancel()
  {
    this.zzaiy.cancel();
  }
  
  public Result get()
  {
    boolean bool = isDone();
    if (bool)
    {
      TimeUnit localTimeUnit = TimeUnit.MILLISECONDS;
      return await(0L, localTimeUnit);
    }
    IllegalStateException localIllegalStateException = new java/lang/IllegalStateException;
    localIllegalStateException.<init>("Result is not available. Check that isDone() returns true before calling get().");
    throw localIllegalStateException;
  }
  
  public boolean isCanceled()
  {
    return this.zzaiy.isCanceled();
  }
  
  public boolean isDone()
  {
    return this.zzaiy.isReady();
  }
  
  public void setResultCallback(ResultCallback paramResultCallback)
  {
    this.zzaiy.setResultCallback(paramResultCallback);
  }
  
  public void setResultCallback(ResultCallback paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    this.zzaiy.setResultCallback(paramResultCallback, paramLong, paramTimeUnit);
  }
  
  public void zza(PendingResult.zza paramzza)
  {
    this.zzaiy.zza(paramzza);
  }
  
  public Integer zzpa()
  {
    return this.zzaiy.zzpa();
  }
}


/* Location:              C:\Users\haryo\Desktop\enjarify-master\presensi-enjarify.jar!\com\google\android\gms\common\api\internal\zzr.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */