package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.TransformedResult;
import com.google.android.gms.common.internal.zzx;
import java.util.concurrent.TimeUnit;

public class zzt
  extends PendingResult
{
  private final Status zzUX;
  
  public zzt(Status paramStatus)
  {
    String str = "Status must not be null";
    zzx.zzb(paramStatus, str);
    boolean bool = paramStatus.isSuccess();
    if (!bool) {
      bool = true;
    }
    for (;;)
    {
      zzx.zzb(bool, "Status must not be success");
      this.zzUX = paramStatus;
      return;
      bool = false;
      str = null;
    }
  }
  
  public Result await()
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
  
  public Result await(long paramLong, TimeUnit paramTimeUnit)
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
  
  public void cancel()
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
  
  Status getStatus()
  {
    return this.zzUX;
  }
  
  public boolean isCanceled()
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
  
  public void setResultCallback(ResultCallback paramResultCallback)
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
  
  public void setResultCallback(ResultCallback paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
  
  public TransformedResult then(ResultTransform paramResultTransform)
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
  
  public void zza(PendingResult.zza paramzza)
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
  
  public Integer zzpa()
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
}


/* Location:              C:\Users\haryo\Desktop\enjarify-master\presensi-enjarify.jar!\com\google\android\gms\common\api\internal\zzt.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */